import { describe, expect, it } from "vitest";
import { renderInputsConf, renderServerConf } from "../../../packages/services/splunk/lib/splunk-render.mjs";

describe("splunk-render", () => {
  it("renders server.conf with serverName and mgmt port", () => {
    const text = renderServerConf({ serverName: "splunk-a", mgmtPort: 8089 });
    expect(text).toContain("serverName = splunk-a");
    expect(text).toContain("mgmtHostPort = 0.0.0.0:8089");
    expect(text).toContain("# Generated by hdc splunk package");
  });

  it("renders empty inputs stub when no inputs", () => {
    const text = renderInputsConf([]);
    expect(text).toContain("No custom inputs");
  });

  it("renders inputs stanzas", () => {
    const text = renderInputsConf([
      { name: "monitor:///var/log/syslog", disabled: 0, index: "main" },
    ]);
    expect(text).toContain("[monitor:///var/log/syslog]");
    expect(text).toContain("index = main");
  });
});
